# Output settings
exp_name: debug
notes: ""

# General settings
gpus: [6]
seed: 1
train_batch_size: 2
debug: True

# General training hyperparameters
ral_initial_alpha: 0.
ral_final_alpha: 0.
radius_conf_loss: 0.
radius_label_smoothing: False

# Training hyperparameters
model: euclidean-poincare
dataset: cocostuff10k
model_size: b0

# Logging
wandb: False

# Test
# checkpoint_path: "code/segmentation/output/cityscapes/best_epoch-epoch=28_val_mIoU-val_mIoU=42.71.ckpt"
test_batch_size: 2