# General settings
gpus: [0]
seed: 1
debug: False

# Training hyperparameters
model: euclidean-poincare
dataset: cocostuff10k
model_size: b0

# Logging
wandb: False
debug: False

# Test
checkpoint_path: "code/segmentation/output/cocostuff10k/EP-Segformer-b0_20epochs/best_epoch=18_val_mIoU=10.75.ckpt"
test_batch_size: 6