# Output settings
exp_name: EP-Segformer
notes: ""

# General settings
gpus: [0,1,2,3]
seed: 1
batch_size: 4

# General training hyperparameters
ral_initial_alpha: 0.
ral_final_alpha: 0.
radius_conf_loss: 0.
radius_label_smoothing: False

# Training hyperparameters
model: euclidean-poincare
dataset: Cityscapes

# Logging
wandb: False