# Output settings
exp_name: EP-Segformer-b5_RAL1
notes: ""

# General settings
gpus: [0,1,2,3,4,5]
seed: 1
train_batch_size: 6
debug: False
model_size: b5

# General training hyperparameters
ral_initial_alpha: 1.
ral_final_alpha: 1.
radius_conf_loss: 0.
radius_label_smoothing: False

# Training hyperparameters
model: euclidean-poincare
dataset: cityscapes

# Logging
wandb: True

# Test
test_batch_size: 6