dataset: cocostuff10k
data_root: code/segmentation/data/cocostuff10k

# General training hyperparameters
num_epochs: 10
batch_size: 2
lr: 6e-5
weight_decay: 1e-2
use_lr_scheduler: True
lr_scheduler: CosineAnnealingLR             # CosineAnnealingLR or MultiStepLR
lr_scheduler_milestones: [60, 120, 160]
lr_scheduler_gamma: 0.2
base_loss: cross_entropy               # cross_entropy or focal_loss

# General validation/testing hyperparameters
batch_size_test: 2
validation_split: False