# Output settings
exp_name: L-ResNet18_RAL01
notes: ""

# General settings
gpus: [0,1,2,3]
seed: 1

# General training hyperparameters
ral_initial_alpha: .1
ral_final_alpha: .1
radius_conf_loss: .0
radius_label_smoothing: False

# Training configs
model: lorentz
dataset: Tiny-ImageNet

# Logging
wandb: True